apiVersion: v1
kind: Service
metadata:
  name: tmdb-proxy
  labels:
    app: tmdb-proxy
spec:
  selector:
    app: tmdb-proxy
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
