version: '3.5'

services:
  tmdb_db:
    image: mongo:4.0
    container_name: tmbd_db
    restart: unless-stopped
    volumes:
      - ./docker/data/demo_db:/data/db

  tmdb_server:
    image: adrianrdurran/tmdb-staging:dev
    # build:
    #   context: ./server
    container_name: tmdb_server
    restart: unless-stopped
    # volumes:
    #   - ./server:/usr/src/app
    #   - /usr/src/app/node_modules/

    env_file:
      - ./server/server.env
    ports:
      - 3050:3050
    depends_on:
      - tmdb_db
    environment:
      WAIT_HOSTS: tmdb_db:27017

  tmdb_proxy:
    build: ./proxy
    links:
      - tmdb_server
    ports:
      - 8080:8080
