version: "3.5"

services:
  tmdb-db:
    image: mongo:4.0
    container_name: tmbd-db
    restart: unless-stopped
    volumes:
      - ./docker/data/demo_db:/data/db

  tmdb-server:
    image: adrianrdurran/tmdb-staging:dev
    # build:
    #   context: ./server
    container_name: tmdb-server
    restart: unless-stopped
    # volumes:
    #   - ./server:/usr/src/app
    #   - /usr/src/app/node_modules/

    env_file:
      - ./server/server.env
    ports:
      - 3050:3050
    depends_on:
      - tmdb_db
    environment:
      WAIT_HOSTS: tmdb-db:27017
  tmdb-proxy:
    image: adrianrdurran/tmdb-proxy:latest
    links:
      - tmdb-server
    ports:
      - 80:80
      - 443:443
