version: '3.5'

services:
  tmdb_server:
    build:
      context: ./server
    container_name: tmdb_server
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/

    env_file:
      - ./server/server.env
    ports:
      - 3050:3050
    depends_on:
      - tmdb_db
    command: ['nodemon', 'index.js']

  tmdb_db:
    image: mongo:latest
    container_name: tmbd_db
    restart: unless-stopped
    volumes:
      - ./docker/data/demo_db:/data/db
