version: '3.5'

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    container_name: tmdb_server
    env_file:
      - server.env
    ports:
      - 3050:3050
    depends_on:
      - db
    command: ['nodemon', 'index.js']
    # networks:
    #   - tmdb

  db:
    image: mongo:latest
    volumes:
      - ./docker/data/db:/data/db
    # networks:
    #   - tmdb
    container_name: tmbd_db
# networks:
#   tmdb:
