version: "3"

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    env_file:
      - server.env
    ports:
      - 3050:3050
    depends_on:s
      - db
    command: ["nodemon", "index.js"]
    networks:
      - tmdb

  db:
    image: mongo:latest
    volumes:
      - ./docker/data/db:/data/db
    networks:
      - tmdb

networks:
  tmdb: