version: "3.7"

services:
  tmdb-db:
    image: mongo:latest
    container_name: tmbd-db
    restart: unless-stopped
    volumes:
      - ./docker/data/db:/data/db

  tmdb-server:
    # the image is for testing on a vm...
    # and also for k8s
    # image: adrianrdurran/tmdb-staging:dev
    build:
      context: ./server
    container_name: tmdb-server
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
      - ./docker/data/images:/usr/src/app/public/images

    env_file:
      - ./server/server.env
    ports:
      - 3050:3050
    depends_on:
      - tmdb-db
    environment:
      WAIT_HOSTS: tmdb-db:27017
  # this is for test purposes on a vm will also use similar for
  # k8s nginx LoadBalancer
  # tmdb-proxy:
  #   image: adrianrdurran/tmdb-proxy:latest
  #   links:
  #     - tmdb-server
  #   ports:
  #     - 80:80
  #     - 443:443
